### ISSUE TITLE
PLEASE MAKE A BINARY!!! 

### ISSUE THREAD

**Issue by happymimimix** [RedCursorSecurityConsulting/PPLKiller#12]
Why no binary files? 
Please compile one and upload ASAP

**Comment by ibay770** [comment]
https://github.com/ibay770/PPLKiller/releases/download/0.1/pplkiller.zip

**Comment by happymimimix** [comment]
You came too late, I got visual studio 2019 and compiled it myself already. 
But thanks anyways. 

Also, you better put that file in releases as well so more people can see it.

**Comment by ibay770** [comment]
It's in the releases in the fork I made, I can't add it to this one.
